{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.paw",
    "module": "pantographsandwires-neoforge",
    "version": "1.21.1-beta-0.2.2-C6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-beta-0.2.2-C6.jar",
          "url": "pantographsandwires-neoforge-1.21.1-beta-0.2.2-C6.jar",
          "size": 2017180,
          "sha512": "5ed5f48791aa9108411335457beacf67803c91dea161b05d332a10ad426220a69256f1f1268a820109a7ed0e1d71fdb1a17289c2a5c86173ffd030b00c09ccab",
          "sha256": "b9908e283b33697c7b3608629967ae01c8dc2c119a047e3d4ce2569061b50099",
          "sha1": "a52deb44d08f0131eb75dbc36c152110846f0843",
          "md5": "ae7f88d2bfecd050a9ef3a98bd6207dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.7-159"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.66"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.6-beta-37"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.9-neoforge"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-neoforge",
          "version": {
            "requires": "1.21.1-beta-3.0.24"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-neoforge-1.21.1",
          "version": {
            "requires": "4.8.4"
          }
        },
        {
          "group": "com.eliotlash.mclib",
          "module": "mclib",
          "version": {
            "requires": "20"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-beta-0.2.2-C6.jar",
          "url": "pantographsandwires-neoforge-1.21.1-beta-0.2.2-C6.jar",
          "size": 2017180,
          "sha512": "5ed5f48791aa9108411335457beacf67803c91dea161b05d332a10ad426220a69256f1f1268a820109a7ed0e1d71fdb1a17289c2a5c86173ffd030b00c09ccab",
          "sha256": "b9908e283b33697c7b3608629967ae01c8dc2c119a047e3d4ce2569061b50099",
          "sha1": "a52deb44d08f0131eb75dbc36c152110846f0843",
          "md5": "ae7f88d2bfecd050a9ef3a98bd6207dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-beta-0.2.2-C6-sources.jar",
          "url": "pantographsandwires-neoforge-1.21.1-beta-0.2.2-C6-sources.jar",
          "size": 1015849,
          "sha512": "f1755d5d66d1d924872d889104990beb301def71c82de798470ad89296d970c3fdecf0573fbdd063ab38c894543d0611a4b67cf0dd973f265b09209b3760c625",
          "sha256": "415f79bf0fb47f7759ad7a26098db2d739177b4e52d09098c4d67bc05ab3dbf9",
          "sha1": "40e1e6fe430fa72bc029d7cf41ed0a01a7bf73c0",
          "md5": "294f4291eef32cce7e14b341631c427d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-beta-0.2.2-C6-javadoc.jar",
          "url": "pantographsandwires-neoforge-1.21.1-beta-0.2.2-C6-javadoc.jar",
          "size": 112206,
          "sha512": "d102827e453191500f4ac76c56be99c4cbec6368e9bd468675303af90bbbb7dda7a6ecf1ca2a4a0428658f93e9aee74a4eb5ba967e5157e7b3c013dd073f2645",
          "sha256": "dae8383d1ff0189bc4b783ad6ccb279817e25b84baac99231e3dd93cd1e760d6",
          "sha1": "48bb4b03cae6b85f6201ddf69caf0f8cd823e0b3",
          "md5": "e2c539851776ec80a58c2ae5d52e9c7a"
        }
      ]
    }
  ]
}
