{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.crn",
    "module": "createrailwaysnavigator-fabric",
    "version": "1.20.1-beta-0.9.0-C6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.0-C6.jar",
          "url": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.0-C6.jar",
          "size": 2045739,
          "sha512": "c8b8d765c9caf5a2501ad191ffc5ed3f99e7c8219365c787bfb4d274fea7f18b35de4f3c302824008fe3c002fb9c08ff5c60b4e5096afa77054c672a1365b837",
          "sha256": "eb4403dd5439a83d5e117890bea8a0727cd9b7991816e2d02a3a948b9ef51ba5",
          "sha1": "1c7e851677054919e67f7b2e76e32fdb2e94011d",
          "md5": "d0828f8cef7eb8f4f1e52191937ad861"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.20.1-beta-3.0.21"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric-1.20.1",
          "version": {
            "requires": "6.0.7.0+mc1.20.1-build.1716"
          }
        }
      ],
      "files": [
        {
          "name": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.0-C6.jar",
          "url": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.0-C6.jar",
          "size": 2045739,
          "sha512": "c8b8d765c9caf5a2501ad191ffc5ed3f99e7c8219365c787bfb4d274fea7f18b35de4f3c302824008fe3c002fb9c08ff5c60b4e5096afa77054c672a1365b837",
          "sha256": "eb4403dd5439a83d5e117890bea8a0727cd9b7991816e2d02a3a948b9ef51ba5",
          "sha1": "1c7e851677054919e67f7b2e76e32fdb2e94011d",
          "md5": "d0828f8cef7eb8f4f1e52191937ad861"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.0-C6-sources.jar",
          "url": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.0-C6-sources.jar",
          "size": 28342,
          "sha512": "30fe5449a6bde88df288e6976ec2a5d4061b73d4f0c34c0125730da930afbf76b5b87062ff993d6ecd6762d2bb4eefca9556aab5cbb17affbddb066b6fcf5e5d",
          "sha256": "b50c322774726feb88d149b1218ce6f817fcca0a83f9e82bc81b5a0770d588c8",
          "sha1": "a091340700375bd34ec4ed10333d62f52f947d8f",
          "md5": "b59d4c7809cf1c1485acdaea958c2ce2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.0-C6-javadoc.jar",
          "url": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.0-C6-javadoc.jar",
          "size": 128280,
          "sha512": "b3ae9af6ec5f0510d806da219fbdd17f7a02c3e668dda9c714c783e59f89cd0799f95779b4ca458a0e30900ae1c9ee6c2b0ee6c0ba1c53fd63e3f78118057011",
          "sha256": "55cfe31e7e0b9fcb0db07c6fa20851ab2e5420225035655a46df882fd661491a",
          "sha1": "9be0ed4c0701cd9b4213e745fc4b90946c7ad937",
          "md5": "8395f43dd5d5323b527398c74a9282ab"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.0-C6-dev-shadow.jar",
          "url": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.0-C6-dev-shadow.jar",
          "size": 2032667,
          "sha512": "d0d9af05dca77d2feda0fa12d19e2e22fe21c61b0d3351a0f548ec3288fae39a34449daaa89b96c2b0631c48adcca5afe170bb0cb6574aa88a9a5268ca9d9880",
          "sha256": "b8ce7726582b30631a443bfea07604489c67d9bb90042dc317213c8fd9928ce9",
          "sha1": "c026c63aed4bf0aa80f1977c965c10dde39788f9",
          "md5": "4acfcf0a7c43f26811075ee86a9ef8ed"
        }
      ]
    }
  ]
}
