{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.14.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.14.jar",
          "size": 2105783,
          "sha512": "573c70bff87aad0aa151525cc00120d2faaf794fb8a66fbe2ec586a71a10428f6ab4cfe50a01fd001a991e5e6c55a8ae192ed87f2bbcdeccbf6d5df7dfc4a243",
          "sha256": "890d1f6622dceb4e843c9d0f310c4685aa212352206de4cf3450de48a258e1e0",
          "sha1": "1038265c2f891d759542a50fc5f4d391ac1ba689",
          "md5": "a6daf588c37c7db01b750cf5dec20bde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.14.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.14.jar",
          "size": 2105783,
          "sha512": "573c70bff87aad0aa151525cc00120d2faaf794fb8a66fbe2ec586a71a10428f6ab4cfe50a01fd001a991e5e6c55a8ae192ed87f2bbcdeccbf6d5df7dfc4a243",
          "sha256": "890d1f6622dceb4e843c9d0f310c4685aa212352206de4cf3450de48a258e1e0",
          "sha1": "1038265c2f891d759542a50fc5f4d391ac1ba689",
          "md5": "a6daf588c37c7db01b750cf5dec20bde"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.14-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.14-sources.jar",
          "size": 629335,
          "sha512": "d70a6296cb80d8c756300389449356a579b1dc2d42f848c7a2b1ce319b4c04193a3b0d5fa7c58a26693539e6dd06cf128fe4bb277e00edacf1e00609005b22ad",
          "sha256": "9d05feddb30adefd8f5727425044a577a6e77008d9b8aeeace3c39ca8ffb25f6",
          "sha1": "589c90d957f373596cb4206d666f989cd4c820fe",
          "md5": "ea15b8a8179647d80fd97faa7fab82bd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.14-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.14-javadoc.jar",
          "size": 262178,
          "sha512": "9f3985d415cbc904d986bc3b9f9b77266887015fc298d7a5c4ef024fe333aefb2901037356673ef1673d608000c6fcea4bc4be14be9456e4bf46339ac83f7c08",
          "sha256": "f808716f15873e6d325919f4a89f7e825d432a7ef30fdbaab9941c2c4e6ed84b",
          "sha1": "a27e82ecef93565989855a8df56ce326b396a2c9",
          "md5": "2ed8878b27874147482ed3e2fb54c8c7"
        }
      ]
    }
  ]
}
