{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.1-beta-3.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.19.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.19.jar",
          "size": 1955455,
          "sha512": "6f5c1bc0e5c6b6eb1b3c43705d5c407684a93efbfa3622c54256bc4aa484455c63113b4c30db1244e11ede5b06d6c19e59e22db33eeaeb23b414cc147130923d",
          "sha256": "42dbddd3ed15748c09a775551b6370968b0e3f9bc540d707a6843e87ae6415d6",
          "sha1": "ce3204f8f59f3870fa9c0a596bc04432c0489831",
          "md5": "df55eb975a7c65fb3a65996fa2c2a2d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.19.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.19.jar",
          "size": 1955455,
          "sha512": "6f5c1bc0e5c6b6eb1b3c43705d5c407684a93efbfa3622c54256bc4aa484455c63113b4c30db1244e11ede5b06d6c19e59e22db33eeaeb23b414cc147130923d",
          "sha256": "42dbddd3ed15748c09a775551b6370968b0e3f9bc540d707a6843e87ae6415d6",
          "sha1": "ce3204f8f59f3870fa9c0a596bc04432c0489831",
          "md5": "df55eb975a7c65fb3a65996fa2c2a2d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.19-sources.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.19-sources.jar",
          "size": 853101,
          "sha512": "cb9ed73079437a7800cacff961ca398674397e7b83df6fd52b0320c2dcc0ea92112a86ed10c72ac36d861709f05281637a6d98421feb79a731d3842c1c67b3c6",
          "sha256": "7fd72f5124eaff0ea95a8b0ab1b8c8a91bbfa2d61fdd8bbf0343aef44176c7e8",
          "sha1": "b919770ce9b9ad51ba13e05f0a4b37ab8eedb36c",
          "md5": "3579714198f3feaf4ec52e923a7f675e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.19-javadoc.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.19-javadoc.jar",
          "size": 170962,
          "sha512": "6f2c6b383cef829255aef047d55fd1216cb36ade25e7f09aea75177e330c20e95fca099287bb902f131d3f162e4bee965ffc5fc9e658e655033e591333aae93e",
          "sha256": "542c7f66129c34dd48406a37a5c59e33fd75ef06739e5ed9da05ac6884fb0186",
          "sha1": "181a677ad086202e12c62c3b8a811814335de47a",
          "md5": "e5fb01d32792bd211dcf173bbe3ec36a"
        }
      ]
    }
  ]
}
