{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.crn",
    "module": "createrailwaysnavigator-forge",
    "version": "1.20.1-beta-0.10.0-C6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "createrailwaysnavigator-forge-1.20.1-beta-0.10.0-C6.jar",
          "url": "createrailwaysnavigator-forge-1.20.1-beta-0.10.0-C6.jar",
          "size": 4676758,
          "sha512": "b4e397091bd2ed65f2a57741ce886f3811604cd4ab0a41ddc3c3daf1cfc9bd4a4651ad6764915dd59ef7cf11ff760108df49759fbdbe9855e9f48c8541b4ac87",
          "sha256": "8ad5fbe8fe1a79d87269f397ead48c35b7e45946b7b862b7f195f45b6f16a2e7",
          "sha1": "594f9d0db8ab40b48d0e339dfcffa3f22b3beb05",
          "md5": "ee73e0cd513d74b45789c985f7ba2541"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.20.1-beta-3.0.28"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.106"
          }
        },
        {
          "group": "curse.maven",
          "module": "time-control-303570",
          "version": {
            "requires": "5095704"
          }
        },
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "5180900"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tramways",
          "version": {
            "requires": "0.3.3-forge"
          }
        }
      ],
      "files": [
        {
          "name": "createrailwaysnavigator-forge-1.20.1-beta-0.10.0-C6.jar",
          "url": "createrailwaysnavigator-forge-1.20.1-beta-0.10.0-C6.jar",
          "size": 4676758,
          "sha512": "b4e397091bd2ed65f2a57741ce886f3811604cd4ab0a41ddc3c3daf1cfc9bd4a4651ad6764915dd59ef7cf11ff760108df49759fbdbe9855e9f48c8541b4ac87",
          "sha256": "8ad5fbe8fe1a79d87269f397ead48c35b7e45946b7b862b7f195f45b6f16a2e7",
          "sha1": "594f9d0db8ab40b48d0e339dfcffa3f22b3beb05",
          "md5": "ee73e0cd513d74b45789c985f7ba2541"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createrailwaysnavigator-forge-1.20.1-beta-0.10.0-C6-sources.jar",
          "url": "createrailwaysnavigator-forge-1.20.1-beta-0.10.0-C6-sources.jar",
          "size": 1490887,
          "sha512": "de987cc3f2181bbbef370e7270caccba064dc94695449bbda33ee823bb5493ee5de63723e57d379e87f97944db110a77d6e44a3a20e01d1fabd61798c2df4a7c",
          "sha256": "30765ebe3490360b337540f841e7ec755607df41b53e1372b6a9c37e68c7c542",
          "sha1": "38c3f8d3918fddc3a3443e717a0432d43a821243",
          "md5": "02e4a9f0bc72ff84cf967f002568a383"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createrailwaysnavigator-forge-1.20.1-beta-0.10.0-C6-javadoc.jar",
          "url": "createrailwaysnavigator-forge-1.20.1-beta-0.10.0-C6-javadoc.jar",
          "size": 107440,
          "sha512": "0602c649895b8631238f556e7825839b20c31d9b335644d7173302c48fa09fa64d91f6d02bf324961d8ec584ae40c2ee5d248e387768de4d359f841541de18bb",
          "sha256": "4edfdd35af8f059fd32e17f87daf8c48b511b93f8dc9640e43d36b78be8115fb",
          "sha1": "a6dc52f2a5e37c9fd3b8d80175eebe3bb35309af",
          "md5": "fd1dd23a8e5eaf31076f718af02949b2"
        }
      ]
    }
  ]
}
