{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.paw",
    "module": "pantographsandwires-forge",
    "version": "1.20.1-beta-0.2.1-C6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pantographsandwires-forge-1.20.1-beta-0.2.1-C6.jar",
          "url": "pantographsandwires-forge-1.20.1-beta-0.2.1-C6.jar",
          "size": 4920025,
          "sha512": "bd41c010757cd127afe74558fb53024d8e35c7da537cbe83e84d595f12ac826791f0624f33ad5cf66b348a1f35c8437f4cca30f6af60622b167fd508dce0b741",
          "sha256": "6906cb09bfb6d37d84b10b8a6934aa34a4d2d1cfff6266d9a1b12a486da8e798",
          "sha1": "723e3d0eb41bde28143c882d9c8a973428f4e71b",
          "md5": "fe4e174d7bc1710f6df0f19a7c5df1dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.20.1-beta-3.0.24"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.7-281"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-forge-1.20.1",
          "version": {
            "requires": "4.7"
          }
        },
        {
          "group": "com.eliotlash.mclib",
          "module": "mclib",
          "version": {
            "requires": "20"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.embeddedt",
          "module": "embeddium-1.20.1",
          "version": {
            "requires": "0.3.31-beta.53+mc1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "pantographsandwires-forge-1.20.1-beta-0.2.1-C6.jar",
          "url": "pantographsandwires-forge-1.20.1-beta-0.2.1-C6.jar",
          "size": 4920025,
          "sha512": "bd41c010757cd127afe74558fb53024d8e35c7da537cbe83e84d595f12ac826791f0624f33ad5cf66b348a1f35c8437f4cca30f6af60622b167fd508dce0b741",
          "sha256": "6906cb09bfb6d37d84b10b8a6934aa34a4d2d1cfff6266d9a1b12a486da8e798",
          "sha1": "723e3d0eb41bde28143c882d9c8a973428f4e71b",
          "md5": "fe4e174d7bc1710f6df0f19a7c5df1dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-forge-1.20.1-beta-0.2.1-C6-sources.jar",
          "url": "pantographsandwires-forge-1.20.1-beta-0.2.1-C6-sources.jar",
          "size": 1036681,
          "sha512": "2d9e0e9fe6392f7d10f8a57c8eb89167808db658ad6f0dced65a7c3c371f3551e7b252d02468ca29a5b2bacef3f99ef8e2168fa582e1561ab47af6d605472046",
          "sha256": "1afd1f8b3c2d35d1f0f77288c165df04faf9309e6d34c055a0b4947acbc28ba7",
          "sha1": "25e4c72e2b24f4d1dcff2f73d9b939efcaa46a59",
          "md5": "56a348d7026fd90962fd541e8e069997"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-forge-1.20.1-beta-0.2.1-C6-javadoc.jar",
          "url": "pantographsandwires-forge-1.20.1-beta-0.2.1-C6-javadoc.jar",
          "size": 170411,
          "sha512": "2819fdcc7d0952097a12a229eb1c2b77a46249fa35b79f3432faf569e43b936ca26aa56e378381fbf81a6677ea594b837786085468479a850047f2f57c1fe3c4",
          "sha256": "ef915b9c1f53c5dab2443adeb3ac608961cb3d72a91f18ff0fb12679070ca3cd",
          "sha1": "f85da85af1c6e25cb77241336aec5db1523073d2",
          "md5": "503ab2d16ebc899634265f4eff53b7a1"
        }
      ]
    }
  ]
}
