{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.paw",
    "module": "pantographsandwires-neoforge",
    "version": "1.21.1-beta-0.2.3-C6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-beta-0.2.3-C6.jar",
          "url": "pantographsandwires-neoforge-1.21.1-beta-0.2.3-C6.jar",
          "size": 2030764,
          "sha512": "25fca860cf1767aa8456a7877c44e320718dc95aa80975f66e4914a58f402af7452363cb34b98b252be3d186104f998dee8571220b99dc2c43ee4968cbbce4ef",
          "sha256": "8eb1232e6bfac4e2c3b421f7b8bc39f841fad20b41a1ac77b12a62f0ec0cc79b",
          "sha1": "44ac4b3d476c2a2b824ea8bf4bc8bb124edd74c9",
          "md5": "dce5650558d073ad444aa9aee7a6f709"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.8-169"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.66"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.6-beta-37"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.21.1-0.6.13-neoforge"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "copycats",
          "version": {
            "requires": "3.0.4+mc.1.21.1-neoforge-neoforge"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-neoforge",
          "version": {
            "requires": "1.21.1-beta-3.0.28"
          }
        },
        {
          "group": "curse.maven",
          "module": "more-red-387638",
          "version": {
            "requires": "5763286"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-neoforge-1.21.1",
          "version": {
            "requires": "4.8.4"
          }
        },
        {
          "group": "com.eliotlash.mclib",
          "module": "mclib",
          "version": {
            "requires": "20"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-beta-0.2.3-C6.jar",
          "url": "pantographsandwires-neoforge-1.21.1-beta-0.2.3-C6.jar",
          "size": 2030764,
          "sha512": "25fca860cf1767aa8456a7877c44e320718dc95aa80975f66e4914a58f402af7452363cb34b98b252be3d186104f998dee8571220b99dc2c43ee4968cbbce4ef",
          "sha256": "8eb1232e6bfac4e2c3b421f7b8bc39f841fad20b41a1ac77b12a62f0ec0cc79b",
          "sha1": "44ac4b3d476c2a2b824ea8bf4bc8bb124edd74c9",
          "md5": "dce5650558d073ad444aa9aee7a6f709"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-beta-0.2.3-C6-sources.jar",
          "url": "pantographsandwires-neoforge-1.21.1-beta-0.2.3-C6-sources.jar",
          "size": 1026656,
          "sha512": "a1c9938d19c8aee581e8d130c4c35c598c1f8b5d670b8f3dfe88502908c12ccb20840bb9b39a3fca8167405de0b4e763f44a01ba6e9eec90733fe4d137a8d924",
          "sha256": "ec23deb5cdf9f23e9dcdb178add8f6ab1414d7d1a42d343cd4ea1e825e1b8767",
          "sha1": "bb5c70a37b650d1a125f02902d5524953cd01137",
          "md5": "79b883496d8b0d88a1e5e0aa6c55f504"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-beta-0.2.3-C6-javadoc.jar",
          "url": "pantographsandwires-neoforge-1.21.1-beta-0.2.3-C6-javadoc.jar",
          "size": 112210,
          "sha512": "b1293c82a5406f8504296495dd5a6b3ff9f05f4d13b85de101a20e005d06a55c79749d2c745dce9972b026d63a3ba309d85ff6ae55e2cfa004d607fa1f2b7782",
          "sha256": "820c050648c8076cbd0f83741b9f86595070b908e256fe76069867db87fd404a",
          "sha1": "91fa0a8e7444df821c40acd284ccc5eaf79764b5",
          "md5": "cd15711ed51c5d78c74ab606d83e463c"
        }
      ]
    }
  ]
}
