{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mrjulsen.gradle",
    "module": "ModdingBuildTools",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ModdingBuildTools-1.0.14.jar",
          "url": "ModdingBuildTools-1.0.14.jar",
          "size": 99918,
          "sha512": "3a0317b4164f38ac147126e8ee47041f9ce4d253ae71bdede96715ec93a84b3636500705f4610c1642cccff4888e4b4601be2450281de10ac9c50d2c561b952b",
          "sha256": "577a55b40d9499be920244892ee48e29cf01c18cda90e8c87c92db61c9cd9411",
          "sha1": "6558e4682e1f23f48d923065aa3496ff8fe1a1f8",
          "md5": "3543ff27789883afd7597569edf10986"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ModdingBuildTools-1.0.14.jar",
          "url": "ModdingBuildTools-1.0.14.jar",
          "size": 99918,
          "sha512": "3a0317b4164f38ac147126e8ee47041f9ce4d253ae71bdede96715ec93a84b3636500705f4610c1642cccff4888e4b4601be2450281de10ac9c50d2c561b952b",
          "sha256": "577a55b40d9499be920244892ee48e29cf01c18cda90e8c87c92db61c9cd9411",
          "sha1": "6558e4682e1f23f48d923065aa3496ff8fe1a1f8",
          "md5": "3543ff27789883afd7597569edf10986"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ModdingBuildTools-1.0.14-sources.jar",
          "url": "ModdingBuildTools-1.0.14-sources.jar",
          "size": 6437,
          "sha512": "067f09875eaf1f9398a7cc1cd06d01d2aaad21b2a76619da68ee78a68f58f6f39e498d9bd7e129de4c2c53cf2ce7d388d869e1e93d94198ecf6db47cdd2ceea0",
          "sha256": "229933ea1a2ee40093ad36c2dcb2caf05e706bf8d777fdf5014379a8867eafba",
          "sha1": "b9a1814fd53b3da3697eb86073539d1146c3e7c1",
          "md5": "305e06f7a699f2ecd01b48070494e9c8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ModdingBuildTools-1.0.14-javadoc.jar",
          "url": "ModdingBuildTools-1.0.14-javadoc.jar",
          "size": 261,
          "sha512": "c8081de1a1b7dba5612fda507e228aa02a920bc1051b07bafa8bf46daca5e7ff6bf774d28771f53220c057ba80694a92b0f263743e78309699f3dd62c80b57a2",
          "sha256": "02215728ccd09b462ca139f40414492e269c78366b7556e612e1eb822bd1c65b",
          "sha1": "aa0dd8aec531a96656b3ecef92fe210b04f92a5d",
          "md5": "5e08736839a3388e44839a2a845093a7"
        }
      ]
    }
  ]
}
