{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.1-beta-3.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.16.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.16.jar",
          "size": 1941770,
          "sha512": "ccef078ea0a1e034db6a84a056837212a337414c91a4934dc72bb83b5f8e4673d6ce5e3b7723d54fb5a2bcdf2c8470eebc165d749a6d11d75997fe052b8a9c22",
          "sha256": "e2ac8b9d723133cf45e28af60381f23044cd4506797ce139f7844c467c60b3fa",
          "sha1": "72149231c1e1962dafbd6e62de309cb290643ccd",
          "md5": "475b7c826986da6166d32368a64df30c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.16.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.16.jar",
          "size": 1941770,
          "sha512": "ccef078ea0a1e034db6a84a056837212a337414c91a4934dc72bb83b5f8e4673d6ce5e3b7723d54fb5a2bcdf2c8470eebc165d749a6d11d75997fe052b8a9c22",
          "sha256": "e2ac8b9d723133cf45e28af60381f23044cd4506797ce139f7844c467c60b3fa",
          "sha1": "72149231c1e1962dafbd6e62de309cb290643ccd",
          "md5": "475b7c826986da6166d32368a64df30c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.16-sources.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.16-sources.jar",
          "size": 846511,
          "sha512": "269436aa8997927b567fc12eb36b89a95c4e3494cea6265c956a9f6e7203f539856321e0365628932cc946c91bf0987d8e19db2d2e8955421ca3040c0d83772f",
          "sha256": "0fb45213afaaef9c5992f8beaeb87c3ca92974e8b640544f0652f784f6853c53",
          "sha1": "b4127eae1c00fdce471ee2ab858d4d4d91c2112c",
          "md5": "21d04e34defbc3d30eede58f741c1250"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.16-javadoc.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.16-javadoc.jar",
          "size": 154221,
          "sha512": "96f9644e893db42e4461d76c6ffc57fc2018f89b083dfe841b2efd270664dcaa33df0ed1db6f998156e6cef5be9a371d9d558f8e9d88fbe5ee0ccf80a68abcc4",
          "sha256": "7876a1a28c2f79f3156a581c2fbd014f220ee9fd15dc0f32fc4949321ac615d0",
          "sha1": "0cd8117182db4c9637395d24f2e96ca7d8d2babc",
          "md5": "8d1986aae26f6035a17a077baa810833"
        }
      ]
    }
  ]
}
