{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.1-beta-3.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.14.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.14.jar",
          "size": 1902925,
          "sha512": "33ecb60944ff9e29ea23079da8fea7d062571cdc735a488d76e0d8a5bfc126cd0757e7665e3750ffe68d105d8d992d6b59fe3dd59f05b452cd6da716fd7c3145",
          "sha256": "1f26d592ea98860384b3631faa949561bc9418ace0ed5317b52af90f61e40f98",
          "sha1": "c9c8b07426637e5a78a623b7e83595388e519162",
          "md5": "d92bebad2cf84f652dfd2f04e6ac1e1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.14.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.14.jar",
          "size": 1902925,
          "sha512": "33ecb60944ff9e29ea23079da8fea7d062571cdc735a488d76e0d8a5bfc126cd0757e7665e3750ffe68d105d8d992d6b59fe3dd59f05b452cd6da716fd7c3145",
          "sha256": "1f26d592ea98860384b3631faa949561bc9418ace0ed5317b52af90f61e40f98",
          "sha1": "c9c8b07426637e5a78a623b7e83595388e519162",
          "md5": "d92bebad2cf84f652dfd2f04e6ac1e1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.14-sources.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.14-sources.jar",
          "size": 819546,
          "sha512": "d338a111852e4dc9ac504ec326177ca6c9b243f23a6d5c6649f671381ec3bf79c5164df2f17e413a78634cf90696ada47ea4e71eb4816cc6ec077041b17ded7f",
          "sha256": "edff912319d72386823a1c264905c0063d2905fe6a7a339cc38d16ee2b072254",
          "sha1": "9f2b60210adbed10f7ae2dc75c3605ea95e85507",
          "md5": "2b596bf0a5c28397c925f8719f1c1ba7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.14-javadoc.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.14-javadoc.jar",
          "size": 148214,
          "sha512": "2c87c25e888016fbb51f3c2adf4f4ab0d1fbfc03932ec374edfb84b6a6cf12a767756d287a140a3755262fecd0678279132876ad81e064416def051ef860f577",
          "sha256": "dd699e0de796ec1a4dcd23bb2f2f2b5c2d8029bbe36f2037c27da2aa16571ae0",
          "sha1": "aeccc0512b5eae4b40fb483da87683d1f240a966",
          "md5": "be2e9aec4194b6e529de1f6209a06975"
        }
      ]
    }
  ]
}
