{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.paw",
    "module": "pantographsandwires-fabric",
    "version": "1.20.1-beta-0.2.1-C6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pantographsandwires-fabric-1.20.1-beta-0.2.1-C6.jar",
          "url": "pantographsandwires-fabric-1.20.1-beta-0.2.1-C6.jar",
          "size": 5144960,
          "sha512": "738493ddd8ec08950fa0d8c4a2aab2e74c43fb59563c2925bdc77f692329b927d7e5ae78a5868e374c0bc85ff340fbda82d409984a30fcc2b89273f9116f9868",
          "sha256": "e6ddb386a76eff1a01c12d26b633d87a443a4510059de63724791fca33e39a8c",
          "sha1": "0f8840888bf5e42c6284e2314b40a8d974b18184",
          "md5": "f1cb481286dffcc1725598c2b717f32d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.20.1-beta-3.0.24"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.20.1",
          "version": {
            "requires": "4.7"
          }
        },
        {
          "group": "com.eliotlash.mclib",
          "module": "mclib",
          "version": {
            "requires": "20"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sodium",
          "version": {
            "requires": "mc1.20.1-0.5.13-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "indium",
          "version": {
            "requires": "1.0.36+mc1.20.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric-1.20.1",
          "version": {
            "requires": "6.0.7.0+mc1.20.1-build.1716"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "pantographsandwires-fabric-1.20.1-beta-0.2.1-C6.jar",
          "url": "pantographsandwires-fabric-1.20.1-beta-0.2.1-C6.jar",
          "size": 5144960,
          "sha512": "738493ddd8ec08950fa0d8c4a2aab2e74c43fb59563c2925bdc77f692329b927d7e5ae78a5868e374c0bc85ff340fbda82d409984a30fcc2b89273f9116f9868",
          "sha256": "e6ddb386a76eff1a01c12d26b633d87a443a4510059de63724791fca33e39a8c",
          "sha1": "0f8840888bf5e42c6284e2314b40a8d974b18184",
          "md5": "f1cb481286dffcc1725598c2b717f32d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-fabric-1.20.1-beta-0.2.1-C6-sources.jar",
          "url": "pantographsandwires-fabric-1.20.1-beta-0.2.1-C6-sources.jar",
          "size": 67980,
          "sha512": "bdc2b2fa1608d8fd006332f7d7642d2345c702893986fbc3d0a92eaa426d226d423786e94f40279a78ce383ebfdf0c7427c6d318dd55eeefc51faddc44d8f491",
          "sha256": "3a16b930b8ceb3c59587c7148033f89678d9bfc2acc5b905c39b07eb2d086d31",
          "sha1": "f31a2f21da382609a66b3bad689e125825637dd4",
          "md5": "9869e61962d84bdd63fcfd73ec66e25b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-fabric-1.20.1-beta-0.2.1-C6-javadoc.jar",
          "url": "pantographsandwires-fabric-1.20.1-beta-0.2.1-C6-javadoc.jar",
          "size": 183528,
          "sha512": "3da6414dde646ac28991badf7eb72579e89caf093890c1c84bce9bf0462ff30785b2e3b397067c9c8fb7d49f4566fad367d736aac53e3cee80c5b5badb023c22",
          "sha256": "218373267a44e552034017afdf2a36b2bc419245bde1e87df87db7087898854c",
          "sha1": "48a77bbdc18c3670eaa76569f744f16c5e2fb90f",
          "md5": "4f9efdb974db534d23afd8d3161a1ed3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-fabric-1.20.1-beta-0.2.1-C6-dev-shadow.jar",
          "url": "pantographsandwires-fabric-1.20.1-beta-0.2.1-C6-dev-shadow.jar",
          "size": 1440553,
          "sha512": "48954bff4796e807cab7cef790a35301aa1f950e714362d1d4b79b0b2d7d6baa3b5e4a67681962e49d5e19130979e9bf96335232500867215fc956c45580b40a",
          "sha256": "d50c9f52edd2697f5626dd771c01e589fc12b3c16d4849fc7bd41ad43098ee39",
          "sha1": "316a4e5266a19019f80e49e24b84a0060c8f5a9d",
          "md5": "fe4c08df5e8272465802c8cf6ec56033"
        }
      ]
    }
  ]
}
