{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.paw",
    "module": "pantographsandwires-forge",
    "version": "1.20.1-beta-0.2.3-C6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pantographsandwires-forge-1.20.1-beta-0.2.3-C6.jar",
          "url": "pantographsandwires-forge-1.20.1-beta-0.2.3-C6.jar",
          "size": 2433556,
          "sha512": "dcb364d2d69e0ba280b0515a5177591dd9299ce2838b48e538efadc4bb0eca239c427370d89d7b52a5335b4df1c1fdee32fcf22f886abe34834aa6c68b40eb3e",
          "sha256": "9818e37178d7dec656e1aaecb03d675aaaa6c01b0c12f0cd3d0e9e02fb7f47f4",
          "sha1": "19c28492cf078e116fe406a5ad61dbebb992fe65",
          "md5": "134401d83a655cfff1f4e13b891fe403"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.20.1-beta-3.0.28"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-forge-1.20.1",
          "version": {
            "requires": "4.7"
          }
        },
        {
          "group": "com.eliotlash.mclib",
          "module": "mclib",
          "version": {
            "requires": "20"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.embeddedt",
          "module": "embeddium-1.20.1",
          "version": {
            "requires": "0.3.31-beta.53+mc1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.20.0.106"
          }
        }
      ],
      "files": [
        {
          "name": "pantographsandwires-forge-1.20.1-beta-0.2.3-C6.jar",
          "url": "pantographsandwires-forge-1.20.1-beta-0.2.3-C6.jar",
          "size": 2433556,
          "sha512": "dcb364d2d69e0ba280b0515a5177591dd9299ce2838b48e538efadc4bb0eca239c427370d89d7b52a5335b4df1c1fdee32fcf22f886abe34834aa6c68b40eb3e",
          "sha256": "9818e37178d7dec656e1aaecb03d675aaaa6c01b0c12f0cd3d0e9e02fb7f47f4",
          "sha1": "19c28492cf078e116fe406a5ad61dbebb992fe65",
          "md5": "134401d83a655cfff1f4e13b891fe403"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-forge-1.20.1-beta-0.2.3-C6-sources.jar",
          "url": "pantographsandwires-forge-1.20.1-beta-0.2.3-C6-sources.jar",
          "size": 1045489,
          "sha512": "412e646039cd827644c851ae361927b295cd26d11145c0e7f9e2214e956e2cb1abddfb949f57672a6351e1ba68f06fa12acb40d68d58b72df1b82b16fd3e66e6",
          "sha256": "e2aead1e3b29cfe4a62a0dd143d0784eaf11f989d5c3d2f2553e9928a4084972",
          "sha1": "45ad53b6eaefc77a205cb25836c2f2d1458fbad1",
          "md5": "1ab5583d28a27bb96a233c53a0be0b41"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-forge-1.20.1-beta-0.2.3-C6-javadoc.jar",
          "url": "pantographsandwires-forge-1.20.1-beta-0.2.3-C6-javadoc.jar",
          "size": 170417,
          "sha512": "07509d1132a271308a539e39c814dc1035a0d5b89960a871422addb2a8392dd7561e142e4f77fef047ac8d056c59221bb5e651145f75198b31a4573822980736",
          "sha256": "aae635f37284d7932dcb31e093f67e31880c24f2060449e513af6a239902e36f",
          "sha1": "0b9d7900f1719706d99cc8dcd62e0594f8e6d443",
          "md5": "7b985a05487cc028dbe5ccf78a6c9b86"
        }
      ]
    }
  ]
}
