{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.trafficcraft",
    "module": "trafficcraft-fabric",
    "version": "1.20.1-1.2.0-beta.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "trafficcraft-fabric-1.20.1-1.2.0-beta.2.jar",
          "url": "trafficcraft-fabric-1.20.1-1.2.0-beta.2.jar",
          "size": 4758286,
          "sha512": "9e091823f01d350ef6ff8e2fc6ad05b7adbba9ea54d091bd3bbaefbd58f370fb2fd8fbbf1294230dacab6d3277df8ec56a8ebf1f44e0401657015f422888180e",
          "sha256": "d30488e020a46a44290265c06c751deb7182d3db4e3e07bd34a6d0d9157f3fc1",
          "sha1": "3a808c5c44e440ff33f7a06f112a079ab61762a1",
          "md5": "09545297de43a4d33c7885c5cc99b3d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.20.1-beta-3.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "trafficcraft-fabric-1.20.1-1.2.0-beta.2.jar",
          "url": "trafficcraft-fabric-1.20.1-1.2.0-beta.2.jar",
          "size": 4758286,
          "sha512": "9e091823f01d350ef6ff8e2fc6ad05b7adbba9ea54d091bd3bbaefbd58f370fb2fd8fbbf1294230dacab6d3277df8ec56a8ebf1f44e0401657015f422888180e",
          "sha256": "d30488e020a46a44290265c06c751deb7182d3db4e3e07bd34a6d0d9157f3fc1",
          "sha1": "3a808c5c44e440ff33f7a06f112a079ab61762a1",
          "md5": "09545297de43a4d33c7885c5cc99b3d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "trafficcraft-fabric-1.20.1-1.2.0-beta.2-sources.jar",
          "url": "trafficcraft-fabric-1.20.1-1.2.0-beta.2-sources.jar",
          "size": 29313,
          "sha512": "07e36e67c8635bab6d3989334a2f6d3175f51cf52c56f0bd78a6621aaf31f00d4a61d27ef430df9270c630129add48d42f8d5028c76818df79b4251f13302053",
          "sha256": "f8f33c7f537cbf7f5d1399c17e4c6389532311c3146d3626115e240761ed470d",
          "sha1": "c5f48c2d7ca2afd389df06cd8cc9be1eca6ee271",
          "md5": "2801e26512e5d6e22885810809e15f18"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "trafficcraft-fabric-1.20.1-1.2.0-beta.2-javadoc.jar",
          "url": "trafficcraft-fabric-1.20.1-1.2.0-beta.2-javadoc.jar",
          "size": 94287,
          "sha512": "39135e5d514b7d2bf79d5c027a21ee3a554560774deab4b73914113f955c028dc2c2e4e2ad9d439e6912f259c770edc31030417ae5f6613a9fcea63697d72f0b",
          "sha256": "b7e73f67b24c23d2bb29cfd7d8e7c80fb69b3e811a2fbc8cf8276a5083ce38aa",
          "sha1": "9c7eff551850c2053457c07991690c1e411a7037",
          "md5": "21a18c2abd6bce70b9fc36add66c6f61"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "trafficcraft-fabric-1.20.1-1.2.0-beta.2-dev-shadow.jar",
          "url": "trafficcraft-fabric-1.20.1-1.2.0-beta.2-dev-shadow.jar",
          "size": 4609531,
          "sha512": "614b4101d4523a4eddcc6a7f482c53c9dfa7995444e4034ee1f7d503e91999c210fde8eb082357d7521d71edca1781320561629cd8d93a00f74febb734801c62",
          "sha256": "0012c575baedd81779fcacc6c869cddfb9c69f490c82e88ff450fd4e60c6791c",
          "sha1": "a673563434739b8375e3dbff8a96f29aeef542f9",
          "md5": "d75ebe7b6dd1ed39a0440cbbc8ee2eef"
        }
      ]
    }
  ]
}
