{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.crn",
    "module": "createrailwaysnavigator-fabric",
    "version": "1.20.1-beta-0.9.1-C6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.1-C6.jar",
          "url": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.1-C6.jar",
          "size": 2056541,
          "sha512": "486c475c31b5063a5a5678492728374d5e54eb0802f773098184b1d908263f10612e2bc91edbc6be0f79927b9fca495423f914dd7900438218e46b2c8084aa0f",
          "sha256": "a9101ccf7783182515614bcd3c932531078c6121b5707f9f050e092c2991b529",
          "sha1": "f9a52b50e4260be3563ddff7087067a06cc94105",
          "md5": "ffc5067da57a143a7bbec9bced5db4f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.20.1-beta-3.0.21"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric-1.20.1",
          "version": {
            "requires": "6.0.7.0+mc1.20.1-build.1716"
          }
        }
      ],
      "files": [
        {
          "name": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.1-C6.jar",
          "url": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.1-C6.jar",
          "size": 2056541,
          "sha512": "486c475c31b5063a5a5678492728374d5e54eb0802f773098184b1d908263f10612e2bc91edbc6be0f79927b9fca495423f914dd7900438218e46b2c8084aa0f",
          "sha256": "a9101ccf7783182515614bcd3c932531078c6121b5707f9f050e092c2991b529",
          "sha1": "f9a52b50e4260be3563ddff7087067a06cc94105",
          "md5": "ffc5067da57a143a7bbec9bced5db4f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.1-C6-sources.jar",
          "url": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.1-C6-sources.jar",
          "size": 28342,
          "sha512": "30fe5449a6bde88df288e6976ec2a5d4061b73d4f0c34c0125730da930afbf76b5b87062ff993d6ecd6762d2bb4eefca9556aab5cbb17affbddb066b6fcf5e5d",
          "sha256": "b50c322774726feb88d149b1218ce6f817fcca0a83f9e82bc81b5a0770d588c8",
          "sha1": "a091340700375bd34ec4ed10333d62f52f947d8f",
          "md5": "b59d4c7809cf1c1485acdaea958c2ce2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.1-C6-javadoc.jar",
          "url": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.1-C6-javadoc.jar",
          "size": 128267,
          "sha512": "0b7702e16c22e40f9ab877aeba94fa8ccad79c424ceda7e9ab1115cea7a58c5f51010180e8cda64bfea90fb24c705153623e50702801c496933c927af7b16ab4",
          "sha256": "5cfab8bba7e7d18bf55dabcc3c9f4833dbf47a04cdfff501bac23cb22dc70a11",
          "sha1": "fb8825bcbde7317b949acd3bf0df4350d18005ff",
          "md5": "c02059c6421af5a127b89e58f9afd263"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.1-C6-dev-shadow.jar",
          "url": "createrailwaysnavigator-fabric-1.20.1-beta-0.9.1-C6-dev-shadow.jar",
          "size": 2043427,
          "sha512": "8f47eb72dd85fd94b313f5096c7bf43ba37851dd1843077bd4cff1b8853b221b275dc3010f46e589f4aa816adda028a470f52a8aaa0d54aa61ba919a40004c27",
          "sha256": "ec3178b942f255fe595d43694774c5d3b8a81d051f20d7c3d4a8cf13b707f9db",
          "sha1": "1e83fdd2f4a95cb89a1fa7f22065aebbe81fbe2b",
          "md5": "83c84a41b24553fbcd2d8f4939944c43"
        }
      ]
    }
  ]
}
