{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.paw",
    "module": "pantographsandwires-neoforge",
    "version": "1.21.1-alpha-0.2.0-1-C6+2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-alpha-0.2.0-1-C6+2.jar",
          "url": "pantographsandwires-neoforge-1.21.1-alpha-0.2.0-1-C6+2.jar",
          "size": 1785298,
          "sha512": "a8e9d6a495245d395ce8311c8a8f893c3ec153760b279b172333edb0ee6635a1f90734b05956318f5497850131047663e6c576ab9796bdfa05f9b8ebfeaf895e",
          "sha256": "4c3441faa46bfd9a7ae2b0ba4a269ce4619d5157ef99fc5035d1b2a89c490e3d",
          "sha1": "2a711e4cf5227483c0ac0c5807e2598ca06406c6",
          "md5": "fe32fedca9cdf9cb61094d6427dd68f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.7-159"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.66"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.6-beta-37"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-neoforge",
          "version": {
            "requires": "1.21.1-beta-3.0.23"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-neoforge-1.21.1",
          "version": {
            "requires": "4.8.4"
          }
        },
        {
          "group": "com.eliotlash.mclib",
          "module": "mclib",
          "version": {
            "requires": "20"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-alpha-0.2.0-1-C6+2.jar",
          "url": "pantographsandwires-neoforge-1.21.1-alpha-0.2.0-1-C6+2.jar",
          "size": 1785298,
          "sha512": "a8e9d6a495245d395ce8311c8a8f893c3ec153760b279b172333edb0ee6635a1f90734b05956318f5497850131047663e6c576ab9796bdfa05f9b8ebfeaf895e",
          "sha256": "4c3441faa46bfd9a7ae2b0ba4a269ce4619d5157ef99fc5035d1b2a89c490e3d",
          "sha1": "2a711e4cf5227483c0ac0c5807e2598ca06406c6",
          "md5": "fe32fedca9cdf9cb61094d6427dd68f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-alpha-0.2.0-1-C6+2-sources.jar",
          "url": "pantographsandwires-neoforge-1.21.1-alpha-0.2.0-1-C6+2-sources.jar",
          "size": 816974,
          "sha512": "1520f814a85cb59247ec35408362cfdc8b36fc07a83fcccbfdf7590c1218893c620f51ee7b12d1cbff459e707d6443cef458452d3a4a12e549055e96a5993c30",
          "sha256": "9393c1ef1d49bda97dec6f60f22cccc66adfd012f071161e97f685e1e4e46161",
          "sha1": "8e02664ba11ff41b1020ed149b37e80c79029ed2",
          "md5": "4078a21e1a8fd286e7242b726925ad8c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantographsandwires-neoforge-1.21.1-alpha-0.2.0-1-C6+2-javadoc.jar",
          "url": "pantographsandwires-neoforge-1.21.1-alpha-0.2.0-1-C6+2-javadoc.jar",
          "size": 131793,
          "sha512": "69b260888ebd224095b30f3d5ec1f0b6e0f63810e7d43d287381488592f0cbbd65365cb9abd9e9f8e583e48b98659376797ded4e2b2a7f219d245a244cd5a67f",
          "sha256": "cf4ee558c538eb78c6994e4de718134f3cb645030082390e59c3e14432a2ca06",
          "sha1": "18b2caa053258a48fbfa52c33b42c38368c826f1",
          "md5": "f55fcb537158358c9be34f633acdae74"
        }
      ]
    }
  ]
}
