{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen",
    "module": "GitHubTestMod-fabric",
    "version": "1.20.1-beta-1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GitHubTestMod-fabric-1.20.1-beta-1.2.3.jar",
          "url": "GitHubTestMod-fabric-1.20.1-beta-1.2.3.jar",
          "size": 4732,
          "sha512": "2461cacd611e9096b6c7060cc13adae23a3221b71ede1fa52dc31ebf8cfcb1515a3800ce7f07c8cce38c2e822ef3b897a38fd1b610969e2aea3cddf1b6db01ea",
          "sha256": "ebde2515e1b43e3a62e0868649b8e5978206dbb169d504144d8091200dec83a7",
          "sha1": "81b56623daf0dea5625e872a8cb34b3ccbb2abd8",
          "md5": "8a66ac08b8755ed96b89724b6e94807e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "GitHubTestMod-fabric-1.20.1-beta-1.2.3.jar",
          "url": "GitHubTestMod-fabric-1.20.1-beta-1.2.3.jar",
          "size": 4732,
          "sha512": "2461cacd611e9096b6c7060cc13adae23a3221b71ede1fa52dc31ebf8cfcb1515a3800ce7f07c8cce38c2e822ef3b897a38fd1b610969e2aea3cddf1b6db01ea",
          "sha256": "ebde2515e1b43e3a62e0868649b8e5978206dbb169d504144d8091200dec83a7",
          "sha1": "81b56623daf0dea5625e872a8cb34b3ccbb2abd8",
          "md5": "8a66ac08b8755ed96b89724b6e94807e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GitHubTestMod-fabric-1.20.1-beta-1.2.3-sources.jar",
          "url": "GitHubTestMod-fabric-1.20.1-beta-1.2.3-sources.jar",
          "size": 2701,
          "sha512": "e0b4e92184900c5c62e5e175565a889b16d531ad47e915baf77b855695d91c8c1c1bc16a70638b2df792a0e0b7a3ae4eefe27b60c1b1565545dfe84366e3de1d",
          "sha256": "129120da9da8bb6d7672f9311f17e46825b26a67f82a95c73ea9f7ae07e2118c",
          "sha1": "8e5d457acce7b9e4f137d7a6b3656d0885069634",
          "md5": "b1451278bfafb347096ced8fecd352d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GitHubTestMod-fabric-1.20.1-beta-1.2.3-javadoc.jar",
          "url": "GitHubTestMod-fabric-1.20.1-beta-1.2.3-javadoc.jar",
          "size": 98790,
          "sha512": "d6e9d3b84a5a199ca851db23fc9791315662825d1d0e057ae7f6e3e5098423118bef7a16f0f57ed2884d7fc92027871799ba6a28fe190990463f08417d97b6b0",
          "sha256": "220304d797000405fe499f570b96ba172103557b5189e713fbbc63eb45d535f5",
          "sha1": "8ba55adcac60e832f6f6ea769c5e508ea1b9bc55",
          "md5": "b1efe23394f12b6fcc47fb95067ce669"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GitHubTestMod-fabric-1.20.1-beta-1.2.3-dev-shadow.jar",
          "url": "GitHubTestMod-fabric-1.20.1-beta-1.2.3-dev-shadow.jar",
          "size": 4322,
          "sha512": "00ce533ed24da31cd897c66354a139116b9dfb21fea181a93111e9261b9962174515105810dba65cc87acc093fb0c91b0c3e65c28639aef3b91f4017565ecf5b",
          "sha256": "3d8aa19d2610af8057b81cbf4c051c6e648e6718a5be02688ab9e8d345d0850f",
          "sha1": "00d884809243d95fe9e28e9f2bb436668b023989",
          "md5": "2df8d3163490afd44dc6121fdee0deea"
        }
      ]
    }
  ]
}
