{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen",
    "module": "GitHubTestMod-forge",
    "version": "1.20.1-beta-1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GitHubTestMod-forge-1.20.1-beta-1.2.3.jar",
          "url": "GitHubTestMod-forge-1.20.1-beta-1.2.3.jar",
          "size": 4218,
          "sha512": "96f3012edab1f364ac6fddbaacc3fa89fcae4c5f6f76e0f94b3203d9420db0236014a6dd33484efb249828745ea1acd87bfde316b0735b5629a772894d7613ba",
          "sha256": "1ca408245b08dc8faf2ef839bc4c7abcbf5a5e746df042af105ba7e529e0dd86",
          "sha1": "a58225e968343ca963fceb98f508a5e1e5405b4c",
          "md5": "2f43ba98dbbd889ccb474347aaed921f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "GitHubTestMod-forge-1.20.1-beta-1.2.3.jar",
          "url": "GitHubTestMod-forge-1.20.1-beta-1.2.3.jar",
          "size": 4218,
          "sha512": "96f3012edab1f364ac6fddbaacc3fa89fcae4c5f6f76e0f94b3203d9420db0236014a6dd33484efb249828745ea1acd87bfde316b0735b5629a772894d7613ba",
          "sha256": "1ca408245b08dc8faf2ef839bc4c7abcbf5a5e746df042af105ba7e529e0dd86",
          "sha1": "a58225e968343ca963fceb98f508a5e1e5405b4c",
          "md5": "2f43ba98dbbd889ccb474347aaed921f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GitHubTestMod-forge-1.20.1-beta-1.2.3-sources.jar",
          "url": "GitHubTestMod-forge-1.20.1-beta-1.2.3-sources.jar",
          "size": 2063,
          "sha512": "0766a9cdce036e272ba3fc301a7cfc2dbed0f40661468df5f4918a9653e3d8dd351109f14514e8dca76e7789dc9ebface5c50bd0bad866f5687dcdff6ada8053",
          "sha256": "53fc2cc4bd6795087c75319d5d2abecc3b3e6f308bc500295ad7db08569d2428",
          "sha1": "6fd1e4e3481d088af87cf8d2cad717b92d9de6f0",
          "md5": "76d6106ae91871d497cb2d3429817516"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GitHubTestMod-forge-1.20.1-beta-1.2.3-javadoc.jar",
          "url": "GitHubTestMod-forge-1.20.1-beta-1.2.3-javadoc.jar",
          "size": 91072,
          "sha512": "5c3139529045fe93cf22d548911e93ca05818e8b6de973e3285c4604b8364c216d165e0262761468be0954d5eb128aeb9ad6a6b830a3d3651d854d7bca295cb7",
          "sha256": "4f19bf6047032598110af0cba0c20c856a9900c2f0dd97665b29bece14b689dc",
          "sha1": "71eb8668581b61c6c6db185ba18b4c16fb08e361",
          "md5": "d473eb9ec52547f4a1aaa81cff0a342f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GitHubTestMod-forge-1.20.1-beta-1.2.3-dev-shadow.jar",
          "url": "GitHubTestMod-forge-1.20.1-beta-1.2.3-dev-shadow.jar",
          "size": 4012,
          "sha512": "2cb13e44917a51e26277a88cd47ce34b39b226751276b56db3bb39b76a6b0fc98f3ff06930e697976edf8b10f784c5d442f5fc68fc1ced2f66311d804ee2f078",
          "sha256": "bdffc671a757717d29d05bf58198d48a5f54e458a2ab2d2697cc32e9ed4b3179",
          "sha1": "f6e66381db39c9500dab35f4f003db7f64a701d7",
          "md5": "76c7aacdac6052c19506f5e76d555379"
        }
      ]
    }
  ]
}
