{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen",
    "module": "GitHubTestMod-forge",
    "version": "1.20.1-beta-1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GitHubTestMod-forge-1.20.1-beta-1.2.3.jar",
          "url": "GitHubTestMod-forge-1.20.1-beta-1.2.3.jar",
          "size": 4216,
          "sha512": "895618cc441599cfd78c2b5cdc415a20aedcdfbf3d1dfd9853143026726a5e91728173d41e2ccaeabd8703a6c4f88dc2051276adebfb942e8c95de962820bc9e",
          "sha256": "8dabfe8ae4c421a4af9e47388b2988552d79463a5e81d4da23f4a091198c2d76",
          "sha1": "27231d197ce1ebe45a68687cc853da9005dbc36a",
          "md5": "08421cee5f8a441e07f97a435e5faabc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "GitHubTestMod-forge-1.20.1-beta-1.2.3.jar",
          "url": "GitHubTestMod-forge-1.20.1-beta-1.2.3.jar",
          "size": 4216,
          "sha512": "895618cc441599cfd78c2b5cdc415a20aedcdfbf3d1dfd9853143026726a5e91728173d41e2ccaeabd8703a6c4f88dc2051276adebfb942e8c95de962820bc9e",
          "sha256": "8dabfe8ae4c421a4af9e47388b2988552d79463a5e81d4da23f4a091198c2d76",
          "sha1": "27231d197ce1ebe45a68687cc853da9005dbc36a",
          "md5": "08421cee5f8a441e07f97a435e5faabc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GitHubTestMod-forge-1.20.1-beta-1.2.3-sources.jar",
          "url": "GitHubTestMod-forge-1.20.1-beta-1.2.3-sources.jar",
          "size": 2063,
          "sha512": "c67dca97f82ea3fc864e1ee0a858dee5742b0808874988080a7db37d82752460e36ad89d15464d52a7fe7b707536e4a47a0fb4abf42e7dfea720057aaf9c6fca",
          "sha256": "97667299a3da264356382ed6dec9685dc6dc568d3a098ea79c0fd094f6d01b3c",
          "sha1": "f596fef510f27b20befb8f8a63f74345d7bc2df9",
          "md5": "25f8e0b7aaa5f361db948f60a39e2424"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GitHubTestMod-forge-1.20.1-beta-1.2.3-javadoc.jar",
          "url": "GitHubTestMod-forge-1.20.1-beta-1.2.3-javadoc.jar",
          "size": 91072,
          "sha512": "85325509d5b3d33e124817fd93599a08078d7d1de5a1b2e421750aa10c05320be8bcf9b00a6f060af25207696d197590078f9d6551c0e7ab7ba5201541832144",
          "sha256": "1d68d633e4120f3b33da8f41bfb652d7b0696f8450422208f06c419f9bc74aec",
          "sha1": "25519ba88559d67d3c9327eabb5b52be2873bb1b",
          "md5": "4de59369657e8398f1cc59236e1b52f2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GitHubTestMod-forge-1.20.1-beta-1.2.3-dev-shadow.jar",
          "url": "GitHubTestMod-forge-1.20.1-beta-1.2.3-dev-shadow.jar",
          "size": 4010,
          "sha512": "021f0e7b5d4d99d417b3be1e0065cbe73e3359a755addb924cf06080050e87f8cdddc2067a8515b2dea661e4b6360ea72be326d9ffe8de8db1c2226dd25e9dc1",
          "sha256": "b14c7e7ffd1204116d25f29adc9ab21fa7c890d522003babb821919359d4a27f",
          "sha1": "77c26bcf852e50571553901ba04d33dd93e149ca",
          "md5": "2dd796a6f526142a4c800637e48b84cb"
        }
      ]
    }
  ]
}
